### ISSUE TITLE
Allow failing i2c write

### ISSUE THREAD

**Issue by ArendJan** [MrYsLab/tmx-pico-aio#6]
I'm working on a project where it is possible to have i2c modules attached to the pico, but they might be disconnected.

Currently it will just raise a RuntimeError(https://github.com/MrYsLab/tmx-pico-aio/blob/ea6cfd00e28275cc1e7c4ebceefc5a485cde3952/tmx_pico_aio/tmx_pico_aio.py#L1555 ) and stop the whole program, which is not desirable.

Could it be possible to disable this or have a callback for these errors?
I can implement it, but I'd like your input on how to (pattern), as I'm not a seasoned Python programmer.

**Comment by MrYsLab** [comment]
@ArendJan, I can help you with the coding, but I have a question before proposing a solution. Are the i2c device or devices connected but not responding for some reason, or are they sometimes not physically connected?

**Comment by ArendJan** [comment]
@MrYsLab that would be great, thank you. The second option, they are sometimes not physically connected

**Comment by MrYsLab** [comment]
@ArendJan is Ok, thanks. Do you know if the devices are connected before starting your application? If so, could you pass a parameter into your application that specifies which i2c addresses are currently disconnected and then test those addresses before performing i2c reads and writes?

I am trying to avoid changing the library since your use case is specific to your application.

The Exception is being generated within an internal callback method that traps for an i2c write failure. 
If my suggestion above does not solve your issue, you can fork the code and change it to look as follows:

```
async def _i2c_write_failed(self, data):
        """
        I2c write attempt failed

        :param data: data[0] = i2c_device

        """
        print(f'i2c write failure for i2c address {data[1]})'
```

The application will continue without exit. The data[0] byte holds the i2c port number, and data[1] has the device's i2c address.
If you don't wish to see a message on the console, you can return without doing the print.

Please let me know if this helps solve your issue or if I can help you further.

**Comment by ArendJan** [comment]
@MrYsLab the application does not know if the devices are connected. I'll take your second suggestion and not throw an exception. Thank you!
